version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=protocolo-elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  mysql:
    build: docker-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
    volumes:
      - /home/marauder/test-data:/var/lib/mysql
    ports:
      - 3306:3306

  logstash:
    container_name: 'logstash'
    build: 'logstash'
    links:
      - 'elasticsearch'
      - 'mysql'

  app:
    container_name: 'api-protocolo-integrado'
    build: 'app'
    restart: 'always'
    environment:
      JAVA_OPTS: '-Dfile.encoding=UTF-8 -Xms256M -Xmx1G -Djava.awt.headless=true -XX:+UseG1GC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC'
    ports:
      - 80:8080
    links:
      - 'elasticsearch'

volumes:
  esdata1:
    driver: local
  mysqldata:
    driver: local
